### PR TITLE
BUGFIX: Remove rule for rewriting Node::getNodeType to Node::nodeType

### PR DESCRIPTION
**Pull request by dlubitz**
… as this is not available anymore

### CODE REVIEW

**Comment by bwaidelich** [comment]
I guess this is good to go, but I don't understand what

> this is not available anymore

means?
Wouldn't this fix calls to `Node::getNodeType()` if it existed in some legacy code?

**Comment by dlubitz** [comment]
Yes, but it was rewritten to `$node->nodeType` and we don't have this property anymore on the node

**Comment by dlubitz** [comment]
Yeah, there might be a way to rector this, but I just wanted to remove this wrong migration as it would lead to even more confusion.

**Review by bwaidelich — APPROVED** [review]
RIght, of course. Thanks for the explanation, makes sense

**Pull request merged**
