### PR TITLE
Replace removed Fusion prototypes

### LINKED ISSUE #47: exchange `Neos.Fusion:RawArray` and `Neos.Fusion:Attributes` prototypes
These prototypes are not longer a part of neos after the Update to version 9

The correct prototype in this case would be `Neos.Fusion:DataStructure` as far as I found out

### PR DESCRIPTION
**Pull request by dlubitz**
Replaces Fusion prototypes regarding this list:

* `Neos.Fusion:Array` replaced with `Neos.Fusion:Join`

* `Neos.Fusion:RawArray` replaced with `Neos.Fusion:DataStructure`

* `Neos.Fusion:Collection` replaced with `Neos.Fusion:Loop`

* `Neos.Fusion:RawCollection` replaced with `Neos.Fusion:Map`

https://github.com/neos/neos-development-collection/blob/9.0/Neos.Neos/Documentation/References/NeosFusionReference.rst?plain=1#L1377-L1384

Fixes #47

### CODE REVIEW

**Review by kdambekalns — APPROVED** [review]
👍 by 👀

**Comment by mhsdesign** [comment]
hi thanks for this pr but as @mficzel and me discussed we need to have a comment explaining the full implications of this rename as the keys cannot be migrated safely. A comment like https://github.com/neos/neos-development-collection/pull/4537#issuecomment-1727191511

```
# @todo the key `children` has to be renamed to `items` which cannot be done automatically
```

might help?

also `Neos.Fusion:Attributes` was removed without replacement.


The full upgrade instruction can also be found inside the pr:

* `Neos.Fusion:Array` replace with `Neos.Fusion:Join`
* `Neos.Fusion:RawArray` replaced with `Neos.Fusion:DataStructure`
* `Neos.Fusion:Collection` replaced with `Neos.Fusion:Loop` and the property `children` has to be renamed to `items`
* `Neos.Fusion:RawCollection` replaced with `Neos.Fusion:Map` and the property `children` has to be renamed to `items`
* `Neos.Fusion:Attributes` replaced by the property `attributes` in `Neos.Fusion:Tag`

**Comment by dlubitz** [comment]
@mhsdesign See #51

**Comment by dlubitz** [comment]
@mhsdesign and see https://github.com/neos/rector/pull/52

**Pull request merged**
