### PR TITLE
TASK: Remove "internal" node properties

### PR DESCRIPTION
**Pull request by kitsunet**
Adds rector migrations for common "underscore" internal property access on nodes.

Related: #neos-development-collection/4208

### CODE REVIEW

**Comment by kitsunet** [comment]
Mmm, these test failures seem unrelated?

**Comment by ahaeslich** [comment]
> Mmm, these test failures seem unrelated?

Sure are. I stumbled upon them with my PR and as I investigated the last successful run was with this commit: https://github.com/neos/rector/commit/d3cc877a2ba816db303c13dfe8c84ef4f5ff1242

**Comment by ahaeslich** [comment]
Upon further investigation using `phpstan/phpstan` in version 1.10.13 the tests are green again on main. 

Next step in this 🐰 hole: why can't we relax the requirement?

**Review by dlubitz — COMMENTED** [review]
@kitsunet Thanks for taking care. Could you please add the new cases to the existing tests? 

E.g here for _depth:
https://github.com/neos/rector/blob/main/tests/ContentRepository90/Rules/FusionNodeDepthRector/Fixture/some_file.fusion.inc

**Review by dlubitz — APPROVED** [review]

**Pull request merged**
